### ISSUE TITLE
Question about version pinning

### ISSUE THREAD

**Issue by johbo** [contentful/contentful.py#1]
I am currently integrating the client into a web project and I faced some challenges due to the version pinning inside of the file `setup.py`:

```
    'requests==2.12.1',
    'python-dateutil==2.6.0'
```

This is making it tricky to install it together with a set of dependencies which I have already. Would it be an option to relax this and only provide the pinning inside of the file `requirements.txt` as something like a "known good set" ?

**Comment by dlitvakb** [comment]
Sounds good!

I'll do this tomorrow and release a patch version.

Cheers

**Comment by johbo** [comment]
Closing, thanks for merging in the change
