### ISSUE TITLE
Add more None checks to FieldType coerce methods

### ISSUE THREAD

**Issue by thrawny** [contentful/contentful.py#11]
Some FieldType classes have a None check, like so;
```python
class IntegerField(BasicField):
    """Integer Coercion Class"""

    def coerce(self, value):
        """Coerces value to int"""

        return int(value) if value is not None else None
```
However many do not. TextField does not so it will coerce None to "None".
```python
>>> text_field = TextField()
>>> text_field.coerce(None)
>>> "None"
```
Having None in a DateField will result in an exception.
```python
>>> date_field = DateField()
>>> date_field.coerce(None)
>>> TypeError: Parser must be a string or character stream, not NoneType
```

Should not all FieldType classes support None values safely? I would be happy to add tests and implement None checks for every FieldType. Perhaps by moving the None check up to BasicField.

**Comment by paribaker** [comment]
Ignore my previous comment it seems the bug occurred because I created a field with the same key but different type. Since the type is cached it seems the old type is still being used.
