### ISSUE TITLE
python 3?

### ISSUE THREAD

**Issue by sirvon** [contentful/contentful.py#18]
Does this lib apply to python 3.6?

**Comment by dlitvakb** [comment]
Hey @sirvon,

This library is Python 2.7+ and 3.1+ compatible, 3.6 is compatible as well.

Cheers

**Comment by benhoyt** [comment]
In that case it'd be good to add the `Programming Language :: Python :: 3.6` classifier to setup.py, as well as Python 3.6 to the tox/travis config.
