### ISSUE TITLE
Accessor methods return locale identifier

### ISSUE THREAD

**Issue by serra** [contentful/contentful.py#25]
When I use the api.contentful.com to retrieve an entry, it loads the following dict into `_fields`:

```
{'en-US': {'title': "{'en-US': 'Prepare the Big Wall Estimation (1)'}", 'moderated': True, 'image': {'en-US': {'sys': {'type': 'Link', 'linkType': 'Asset', 'id': '6jIWlcxic8IAA0qYqAqymI'}}}, 'description': "{'en-US': 'This preparation allows you to do a the Big Wall Estimation with your team.'}", 'tags': ['en-US'], 'steps': ['en-US'], 'creator': {'en-US': {'sys': {'type': 'Link', 'linkType': 'Entry', 'id': '5oGDjpcUNymKUuIqkko0aQ'}}}, 'practice': {'en-US': {'sys': {'type': 'Link', 'linkType': 'Entry', 'id': 'LWRx0vUZYk6EU2imIAuI8'}}}}}
```

The locale is used as a key in the main dictionary as well as for each field.

In the Python wrapper, this means that I cannot use the accessor methods. E.g. `entry.title` returns  `"{'en-US': 'Prepare the Big Wall Estimation (1)'}"` where I'd expect it to return simply the string `'Prepare the Big Wall Estimation (1)'`.

I'm not sure if this is a bug or if I'm doing something wrong.

I'm using version 1.4.3 of contentful.py.

**Comment by Roblinde** [comment]
api.contentful.com is actually for the Contentful Management API. This SDK is for the Content Delivery API which can be found at cdn.contentful.com.

There is another python SDK specifically for the management API here: https://github.com/contentful/contentful-management.py

**Comment by serra** [comment]
Ah, @Roblinde thanks for the swift response, I missed that.
Maybe you could consider raising a warning of some kind when creating a client using 

```
client = Client(SPACE_ID, ACCESS_TOKEN, api_url='api.contentful.com')
```

Now a lot of functionality just works, but we run into strange behavior like described in this issue.

**Comment by Roblinde** [comment]
That's a great suggestion. I'll look into that!

Thanks!
