### ISSUE TITLE
[feature] Access `validations` information for a ContentType

### ISSUE THREAD

**Issue by eillarra** [contentful/contentful.py#33]
The Content Delivery API returns some basic information about a content type (`required`, `omitted`, ...), but `validations` doesn't seem to be included. This will be a useful thing when we try to dynamically generate forms for a ContentType.

Is there a way of retrieving the same raw JSON we can see at the content type management page?

![Example](https://user-images.githubusercontent.com/514589/42203626-ab088e92-7e9f-11e8-84a3-c91e0771285b.png)

**Comment by dlitvakb** [comment]
Hey @eillarra,

This feature is already available in the CMA SDK, the above mentioned JSON is not available through the CDA, as it may contain information that shouldn't be visible for end consumers of the content.

This SDK only covers CDA. If you want CMA features, please use contentful/contentful-management.py

Cheers
