### ISSUE TITLE
client always returns Keyerror: RichTextField

### ISSUE THREAD

**Issue by jerrytim** [contentful/contentful.py#47]
Following the documentation I use the following code to retrieve all entries with certain content type:
```from contentful import Client
client = Client(space_id=space, access_token=token, environment='master')

entries_by_content_type = client.entries({'content_type': 'article'})
```
it always returns `KeyError: 'RichTextField'`.
Any help?

**Comment by dlitvakb** [comment]
Hey @jerrytim,

Looks like you have an SDK that's previous to version `1.11.1` which introduced the RichText feature.

Please ensure that you have installed a version equal or newer to `1.11.1`.

Cheers

**Comment by jerrytim** [comment]
Thanks! After updated to latest version it works.
