### ISSUE TITLE
Create possibility for sorting and paging

### ISSUE THREAD

**Issue by n-elloco** [contentful/contentful.py#6]
Contetful Delivery API supports possibility for sorting and paging data.
It's necessary to implement these features fot contentful.py client.

**Comment by dlitvakb** [comment]
Hey @n-elloco,

These options are available on the SDK.

For example, to get entries sorted by `updatedAt`:

```python
entries_by_date = client.entries({'order': 'sys.updatedAt'})
```

Second set of 10 entries, on entries paged by tens (make sure to add an order attribute in order to have deterministic results on paging):

```python
second_10_entries = client.entries({'limit': 10, 'skip': 10, 'order': 'sys.updatedAt'})
```

Hope that helps

Cheers

**Comment by n-elloco** [comment]
Thanks for answer. I almost guessed myself. However for sorting I use notation `fields.*` instead of `sys.*`, because with last pattern I have error `BadRequestError: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.`

**Comment by dlitvakb** [comment]
Hey @n-elloco,

For that case you also need to send the `'content_type'` parameter.

Cheers
