### ISSUE TITLE
Cannot retrieve all localized fields 

### ISSUE THREAD

**Issue by mark-mishyn** [contentful/contentful.py#68]
Hi there:)

We are consume Preview API by using the client and we try to localize our entries with *Field-level localization*.

There is our simple content type with 3 fields:

MyContentType:
    - title - Short Text
    - text - Rich Text [localization enabled]
    - story_background - Asset Image

Below is short example that shows a bit strange behavior for me:

```
In [3]: client = contentful.Client('xxxx', 'yyyy', api_url="preview.contentful.com")
In [4]: e = c.entry('piu-piu-xyz')
In [5]: e.fields()
Out[5]: 
{'title': 'My Super Entry',
 'story_background': <Asset id='7sXi0s40LopvArQWPOEugJ' url='//images.ctfassets.net/y0gz53fkm5u0/7sXi0s40LopvArQWPOEugJ/161695276187cdd36f7232d4df167845/Back_1.jpg'>,
 'text': {} # some object with English text 
 }
In [7]: e = c.entry('piu-piu-xyz', {'locale': '*'})
In [8]: e.fields()
Out[8]: {}
In [9]: e.fields(locale='ru')
Out[9]: 
{
 'text': {...}  # Some Russian text, but where is "story_background" and "title"?
}
```

So, my goal is to read all entry fields in all available locales with single API call. Is it possible?

**Comment by dlitvakb** [comment]
Hey @mark-mishyn,

If you want to get all localized fields at the same time, then you can access the underlying fields dictionary, through `entry._fields`.

Cheers

**Comment by mark-mishyn** [comment]
I want to mention that to archive desired behavior I made this `all_fields = entry.fields() | entry.fields(locale='ru')`

@dlitvakb thank you!:)
