### ISSUE TITLE
Contentful Python  "Create Issue" button links to Contentful Ruby issues page.

### ISSUE THREAD

**Issue by EricNelson12** [contentful/contentful.py#74]
This [create an issue button](https://github.com/contentful/contentful.py#you-found-a-bug-or-want-to-propose-a-feature) should link to https://github.com/contentful/contentful.py/issues/new instead of https://github.com/contentful/contentful.rb/issues/new.

![image](https://user-images.githubusercontent.com/10719341/182903864-577a32e7-4c62-4f47-8a11-77b3bde39637.png)

**Comment by rubydog** [comment]
Fixed in #75
