### ISSUE TITLE
IndexError using client.entry when no entry with given id exists

### ISSUE THREAD

**Issue by thrawny** [contentful/contentful.py#8]
This will throw a somewhat confusing IndexError when no entry with the id exists.
```python
client.entry('1234')
```

This is because the entry function assumes something will always exist and tries to return the first item in the result.
```python
return self._get(
    '/entries',
    query
)[0]
```

I propose adding a more descriptive exception, i.e. ```EntryNotFound```. If you like this idea I can submit a PR for it.

**Comment by dlitvakb** [comment]
Hey @thrawny,

Sounds good,

I'll add this to the SDK today as well as the feedback received from #9.

I'll create a release with these 2 things later today.

Cheers
