### ISSUE TITLE
Return objects total count

### ISSUE THREAD

**Issue by n-elloco** [contentful/contentful.py#9]
I would like to organize a pagination on my page. I can pass parameters `limit` and `skip` with query. But, when I receive a response I don't recieve total count of records, although this field is returned folowing by CD API.
I can get all records and then make a slice, but it's a bad practice.
I propose to return total count with objects list.
For example:
```bash
...
>>> client.entries({'limit':10, 'skip': 20})
{
  "items": [
    <Entry[2PqfXUJwE8qSYKuM0U6w8M] id='6dbjWqNd9SqccegcqYq224'>,
    ...
  ],
  "total": 2564
}
```
For now,  I have to make additional request to Content Management API with parameter `limit=0` and get total count from response.

**Comment by dlitvakb** [comment]
Hey @n-elloco,

Sounds like a valid point,

I will wrap Arrays with an object so that you can have this metadata available.

Cheers

**Comment by n-elloco** [comment]
Hello @dlitvakb 
Thank you very much. Great job.
